config/routes.rb
Rails.application.routes.draw do
  resources :dissertations
  resources :abstracts
  resources :contributors
  resources :keywords
  resources :alternative_titles
  resources :creators
  resources :languages
  namespace :admin do
    get 'home/index'
    root 'home#index'
      resources :dissertations
      resources :abstracts
      resources :contributors
      resources :keywords
      resources :alternative_titles
      resources :creators
      resources :languages
  end
  devise_for :users
  get 'home/index'
  get 'home/about'
  resources :blogs
  root "home#index"
end

app/models/abstract.rb
class Abstract < ApplicationRecord
  belongs_to :language
end

app/models/alternative_title.rb
class AlternativeTitle < ApplicationRecord
  belongs_to :language
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/contributor.rb
class Contributor < ApplicationRecord
end

app/models/creator.rb
class Creator < ApplicationRecord
end

app/models/dissertation.rb
class Dissertation < ApplicationRecord
  belongs_to :language
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  belongs_to :language
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/languages_controller.rb
class Admin::LanguagesController < ApplicationController
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  before_action :set_creator, only: %i[ show edit update destroy ]

  # GET /creators or /creators.json
  def index
    @creators = Creator.all
  end

  # GET /creators/1 or /creators/1.json
  def show
  end

  # GET /creators/new
  def new
    @creator = Creator.new
  end

  # GET /creators/1/edit
  def edit
  end

  # POST /creators or /creators.json
  def create
    @creator = Creator.new(creator_params)

    respond_to do |format|
      if @creator.save
        format.html { redirect_to creator_url(@creator), notice: "Creator was successfully created." }
        format.json { render :show, status: :created, location: @creator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creators/1 or /creators/1.json
  def update
    respond_to do |format|
      if @creator.update(creator_params)
        format.html { redirect_to creator_url(@creator), notice: "Creator was successfully updated." }
        format.json { render :show, status: :ok, location: @creator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creators/1 or /creators/1.json
  def destroy
    @creator.destroy

    respond_to do |format|
      format.html { redirect_to creators_url, notice: "Creator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creator
      @creator = Creator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def creator_params
      params.require(:creator).permit(:first_name, :last_name, :sex, :student_code)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page_title = "欢迎！"
  end

  def about
    @page_title = "关于"
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: %i[ show edit update destroy ]

  # GET /languages or /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1 or /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages or /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to language_url(@language), notice: "Language was successfully created." }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1 or /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to language_url(@language), notice: "Language was successfully updated." }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1 or /languages/1.json
  def destroy
    @language.destroy

    respond_to do |format|
      format.html { redirect_to languages_url, notice: "Language was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def language_params
      params.require(:language).permit(:title, :code, :about)
    end
end

app/helpers/abstracts_helper.rb
module AbstractsHelper
end

app/helpers/admin/languages_helper.rb
module Admin::LanguagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/dissertations_helper.rb
module DissertationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_with(model: language) do |form| %>
  <% if language.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
        <% language.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :about, style: "display: block" %>
    <%= form.text_area :about %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/languages/_language.html.erb
<div id="<%= dom_id language %>">
  <p>
    <strong>Title:</strong>
    <%= language.title %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= language.code %>
  </p>

  <p>
    <strong>About:</strong>
    <%= language.about %>
  </p>

</div>

app/views/languages/edit.html.erb
<h1>Editing language</h1>

<%= render "form", language: @language %>

<br>

<div>
  <%= link_to "Show this language", @language %> |
  <%= link_to "Back to languages", languages_path %>
</div>

app/views/languages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Languages</h1>

<div id="languages">
  <% @languages.each do |language| %>
    <%= render language %>
    <p>
      <%= link_to "Show this language", language %>
    </p>
  <% end %>
</div>

<%= link_to "New language", new_language_path %>

app/views/languages/new.html.erb
<h1>New language</h1>

<%= render "form", language: @language %>

<br>

<div>
  <%= link_to "Back to languages", languages_path %>
</div>

app/views/languages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @language %>

<div>
  <%= link_to "Edit this language", edit_language_path(@language) %> |
  <%= link_to "Back to languages", languages_path %>

  <%= button_to "Destroy this language", @language, method: :delete %>
</div>