config/routes.rb
Rails.application.routes.draw do
  resources :dissertations
  resources :abstracts
  resources :contributors
  resources :keywords
  resources :alternative_titles
  resources :creators
  resources :languages
  namespace :admin do
    get 'home/index'
    root 'home#index'
      resources :dissertations
      resources :abstracts
      resources :contributors
      resources :keywords
      resources :alternative_titles
      resources :creators
      resources :languages
  end
  devise_for :users
  get 'home/index'
  get 'home/about'
  resources :blogs
  root "home#index"
end

app/models/abstract.rb
class Abstract < ApplicationRecord
  belongs_to :language
end

app/models/alternative_title.rb
class AlternativeTitle < ApplicationRecord
  belongs_to :language
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/contributor.rb
class Contributor < ApplicationRecord
end

app/models/creator.rb
class Creator < ApplicationRecord
end

app/models/dissertation.rb
class Dissertation < ApplicationRecord
  belongs_to :language
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  belongs_to :language
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  before_action :set_creator, only: %i[ show edit update destroy ]

  # GET /creators or /creators.json
  def index
    @creators = Creator.all
  end

  # GET /creators/1 or /creators/1.json
  def show
  end

  # GET /creators/new
  def new
    @creator = Creator.new
  end

  # GET /creators/1/edit
  def edit
  end

  # POST /creators or /creators.json
  def create
    @creator = Creator.new(creator_params)

    respond_to do |format|
      if @creator.save
        format.html { redirect_to creator_url(@creator), notice: "Creator was successfully created." }
        format.json { render :show, status: :created, location: @creator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creators/1 or /creators/1.json
  def update
    respond_to do |format|
      if @creator.update(creator_params)
        format.html { redirect_to creator_url(@creator), notice: "Creator was successfully updated." }
        format.json { render :show, status: :ok, location: @creator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creators/1 or /creators/1.json
  def destroy
    @creator.destroy

    respond_to do |format|
      format.html { redirect_to creators_url, notice: "Creator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creator
      @creator = Creator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def creator_params
      params.require(:creator).permit(:first_name, :last_name, :sex, :student_code)
    end
end

app/controllers/dissertations_controller.rb
class DissertationsController < ApplicationController
  before_action :set_dissertation, only: %i[ show edit update destroy ]

  # GET /dissertations or /dissertations.json
  def index
    @dissertations = Dissertation.all
  end

  # GET /dissertations/1 or /dissertations/1.json
  def show
  end

  # GET /dissertations/new
  def new
    @dissertation = Dissertation.new
  end

  # GET /dissertations/1/edit
  def edit
  end

  # POST /dissertations or /dissertations.json
  def create
    @dissertation = Dissertation.new(dissertation_params)

    respond_to do |format|
      if @dissertation.save
        format.html { redirect_to dissertation_url(@dissertation), notice: "Dissertation was successfully created." }
        format.json { render :show, status: :created, location: @dissertation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dissertation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dissertations/1 or /dissertations/1.json
  def update
    respond_to do |format|
      if @dissertation.update(dissertation_params)
        format.html { redirect_to dissertation_url(@dissertation), notice: "Dissertation was successfully updated." }
        format.json { render :show, status: :ok, location: @dissertation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dissertation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dissertations/1 or /dissertations/1.json
  def destroy
    @dissertation.destroy

    respond_to do |format|
      format.html { redirect_to dissertations_url, notice: "Dissertation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dissertation
      @dissertation = Dissertation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dissertation_params
      params.require(:dissertation).permit(:title, :language_id, :date_submited)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page_title = "欢迎！"
  end

  def about
    @page_title = "关于"
  end
end

app/helpers/abstracts_helper.rb
module AbstractsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/dissertations_helper.rb
module DissertationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/dissertations/_dissertation.html.erb
<div id="<%= dom_id dissertation %>">
  <p>
    <strong>Title:</strong>
    <%= dissertation.title %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= dissertation.language_id %>
  </p>

  <p>
    <strong>Date submited:</strong>
    <%= dissertation.date_submited %>
  </p>

</div>

app/views/dissertations/_form.html.erb
<%= form_with(model: dissertation) do |form| %>
  <% if dissertation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dissertation.errors.count, "error") %> prohibited this dissertation from being saved:</h2>

      <ul>
        <% dissertation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :language_id, style: "display: block" %>
    <%= form.text_field :language_id %>
  </div>

  <div>
    <%= form.label :date_submited, style: "display: block" %>
    <%= form.date_field :date_submited %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dissertations/edit.html.erb
<h1>Editing dissertation</h1>

<%= render "form", dissertation: @dissertation %>

<br>

<div>
  <%= link_to "Show this dissertation", @dissertation %> |
  <%= link_to "Back to dissertations", dissertations_path %>
</div>

app/views/dissertations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dissertations</h1>

<div id="dissertations">
  <% @dissertations.each do |dissertation| %>
    <%= render dissertation %>
    <p>
      <%= link_to "Show this dissertation", dissertation %>
    </p>
  <% end %>
</div>

<%= link_to "New dissertation", new_dissertation_path %>

app/views/dissertations/new.html.erb
<h1>New dissertation</h1>

<%= render "form", dissertation: @dissertation %>

<br>

<div>
  <%= link_to "Back to dissertations", dissertations_path %>
</div>

app/views/dissertations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dissertation %>

<div>
  <%= link_to "Edit this dissertation", edit_dissertation_path(@dissertation) %> |
  <%= link_to "Back to dissertations", dissertations_path %>

  <%= button_to "Destroy this dissertation", @dissertation, method: :delete %>
</div>