config/routes.rb
Rails.application.routes.draw do
  resources :dissertations
  resources :abstracts
  resources :contributors
  resources :keywords
  resources :alternative_titles
  resources :creators
  resources :languages
  namespace :admin do
    get 'home/index'
    root 'home#index'
      resources :dissertations
      resources :abstracts
      resources :contributors
      resources :keywords
      resources :alternative_titles
      resources :creators
      resources :languages
  end
  devise_for :users
  get 'home/index'
  get 'home/about'
  resources :blogs
  root "home#index"
end

app/models/abstract.rb
class Abstract < ApplicationRecord
  belongs_to :language
end

app/models/alternative_title.rb
class AlternativeTitle < ApplicationRecord
  belongs_to :language
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/contributor.rb
class Contributor < ApplicationRecord
end

app/models/creator.rb
class Creator < ApplicationRecord
end

app/models/dissertation.rb
class Dissertation < ApplicationRecord
  belongs_to :language
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  belongs_to :language
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  before_action :set_contributor, only: %i[ show edit update destroy ]

  # GET /contributors or /contributors.json
  def index
    @contributors = Contributor.all
  end

  # GET /contributors/1 or /contributors/1.json
  def show
  end

  # GET /contributors/new
  def new
    @contributor = Contributor.new
  end

  # GET /contributors/1/edit
  def edit
  end

  # POST /contributors or /contributors.json
  def create
    @contributor = Contributor.new(contributor_params)

    respond_to do |format|
      if @contributor.save
        format.html { redirect_to contributor_url(@contributor), notice: "Contributor was successfully created." }
        format.json { render :show, status: :created, location: @contributor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributors/1 or /contributors/1.json
  def update
    respond_to do |format|
      if @contributor.update(contributor_params)
        format.html { redirect_to contributor_url(@contributor), notice: "Contributor was successfully updated." }
        format.json { render :show, status: :ok, location: @contributor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributors/1 or /contributors/1.json
  def destroy
    @contributor.destroy

    respond_to do |format|
      format.html { redirect_to contributors_url, notice: "Contributor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contributor
      @contributor = Contributor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contributor_params
      params.require(:contributor).permit(:first_name, :last_name, :sex, :professional_title, :about)
    end
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  before_action :set_creator, only: %i[ show edit update destroy ]

  # GET /creators or /creators.json
  def index
    @creators = Creator.all
  end

  # GET /creators/1 or /creators/1.json
  def show
  end

  # GET /creators/new
  def new
    @creator = Creator.new
  end

  # GET /creators/1/edit
  def edit
  end

  # POST /creators or /creators.json
  def create
    @creator = Creator.new(creator_params)

    respond_to do |format|
      if @creator.save
        format.html { redirect_to creator_url(@creator), notice: "Creator was successfully created." }
        format.json { render :show, status: :created, location: @creator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creators/1 or /creators/1.json
  def update
    respond_to do |format|
      if @creator.update(creator_params)
        format.html { redirect_to creator_url(@creator), notice: "Creator was successfully updated." }
        format.json { render :show, status: :ok, location: @creator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creators/1 or /creators/1.json
  def destroy
    @creator.destroy

    respond_to do |format|
      format.html { redirect_to creators_url, notice: "Creator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creator
      @creator = Creator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def creator_params
      params.require(:creator).permit(:first_name, :last_name, :sex, :student_code)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page_title = "欢迎！"
  end

  def about
    @page_title = "关于"
  end
end

app/helpers/abstracts_helper.rb
module AbstractsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/dissertations_helper.rb
module DissertationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/contributors/_contributor.html.erb
<div id="<%= dom_id contributor %>">
  <p>
    <strong>First name:</strong>
    <%= contributor.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= contributor.last_name %>
  </p>

  <p>
    <strong>Sex:</strong>
    <%= contributor.sex %>
  </p>

  <p>
    <strong>Professional title:</strong>
    <%= contributor.professional_title %>
  </p>

  <p>
    <strong>About:</strong>
    <%= contributor.about %>
  </p>

</div>

app/views/contributors/_form.html.erb
<%= form_with(model: contributor) do |form| %>
  <% if contributor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contributor.errors.count, "error") %> prohibited this contributor from being saved:</h2>

      <ul>
        <% contributor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :sex, style: "display: block" %>
    <%= form.text_field :sex %>
  </div>

  <div>
    <%= form.label :professional_title, style: "display: block" %>
    <%= form.text_field :professional_title %>
  </div>

  <div>
    <%= form.label :about, style: "display: block" %>
    <%= form.text_area :about %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contributors/edit.html.erb
<h1>Editing contributor</h1>

<%= render "form", contributor: @contributor %>

<br>

<div>
  <%= link_to "Show this contributor", @contributor %> |
  <%= link_to "Back to contributors", contributors_path %>
</div>

app/views/contributors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contributors</h1>

<div id="contributors">
  <% @contributors.each do |contributor| %>
    <%= render contributor %>
    <p>
      <%= link_to "Show this contributor", contributor %>
    </p>
  <% end %>
</div>

<%= link_to "New contributor", new_contributor_path %>

app/views/contributors/new.html.erb
<h1>New contributor</h1>

<%= render "form", contributor: @contributor %>

<br>

<div>
  <%= link_to "Back to contributors", contributors_path %>
</div>

app/views/contributors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contributor %>

<div>
  <%= link_to "Edit this contributor", edit_contributor_path(@contributor) %> |
  <%= link_to "Back to contributors", contributors_path %>

  <%= button_to "Destroy this contributor", @contributor, method: :delete %>
</div>